pipeline {
    environment {
        // Specify your environment variables.
        APP_VERSION = '1'
    }
    stages {
        stage('Build') {
            steps {
                // Print all the environment variables.
                sh 'printenv'
                sh 'echo $GIT_BRANCH'
                sh 'echo $GIT_COMMIT'
                echo 'Install non-dev composer packages and test a symfony cache clear'
                sh 'docker-compose docker-compose.yml up'
                sh 'docker container ls'
            }
        }
    }
    post {
        always {
            // Always cleanup after the build.
            sh 'docker-compose -f docker-compose.yml down'
            sh 'rm .env'
        }
    }
}